from typing import Annotated, Any, Dict, List, Optional, TypedDict
from langchain_core.messages import AnyMessage
from langgraph.graph import add_messages
import operator

def merge_dicts(left: Dict[str, Any], right: Dict[str, Any]) -> Dict[str, Any]:
    """Reducer to merge two dictionaries by updating keys."""
    return {**(left or {}), **(right or {})}

class AgentState(TypedDict):
    """
    Main state object for the Production RAG v2 system.
    This schema defines the shared memory space used by all agents in the LangGraph.

    Attributes:
        messages (List[AnyMessage]): 
            Standard LangGraph conversation history. Annotated with add_messages 
            to support automatic appending and history management.
        
        msg (Dict[str, Any]): 
            The primary communication channel between the graph and the outside world.
            Contains 'msg_id', 'msg_content', and 'msg_body' (structured data).

        route (Optional[str]): 
            Control signal used by the Router Node. Determines the next node in 
             the graph execution (e.g., 'casual', 'clarify', 'retrieval', 'halting').

        session_id (str): 
            Unique identifier for the current user session. Used for isolating 
            MongoDB records and Redis caches.

        config (Dict[str, Any]): 
            Configuration overrides (e.g., model selection, temperature, 
            or specialized system prompts).

        clarify_count (int): 
            Internal counter to prevent infinite clarification loops with the user.

        summary (Optional[str]): 
            Storage for long-form synthesis (e.g., Meeting Action Items or 
            Research Summaries) generated by specialized worker nodes.

        casual_conv (Dict[str, Any]): 
            Annotated pointer map for non-technical or general chat. 
            Structure: { "msg_id": { "snippet": str, "category": "casual", "timestamp": str } }

        retrieval_conv (Dict[str, Any]): 
            Annotated pointer map for Q&A and RAG operations. 
            Structure: { "msg_id": { "snippet": str, "category": "retrieval", "timestamp": str } }
            Used by Publishing Agent to identify new Q&A pairs for Notion.

        meeting_conv (Dict[str, Any]): 
            Annotated pointer map for transcribed and summarized meetings.
            Structure: { "msg_id": { "snippet": str, "category": "meeting", "timestamp": str } }
            Used by Publishing Agent to identify new meeting notes for Notion.

        publishing_conv (Dict[str, Any]): 
            Internal tracker for data currently in the export pipeline.
            Structure: { "msg_id": { "target_platform": "notion", "status": "pending|done" } }

        notion_workspace (Optional[Dict[str, Any]]): 
            Metadata for the target Notion environment. Essential for Invariant 1 (Source selection).
            Contains:
            - parent_page_id: UUID of the root page containing the workspace.
            - qa_db_id: UUID of the centralized 'Q&A Notes' database.
            - meeting_db_id: UUID of the 'Meeting History' database.
            - target_type: Describes the primary inspection result ('page' or 'database') to switch the agent behavior.
            - workspace_name: Human-readable name (e.g., 'Internal Wiki').
            - last_inspected: Timestamp of the last high-precision discovery.

        last_published_retrieval_ts (str): 
            Transactional marker (ISO Timestamp) for RAG content. 
            Ensures that only new Q&A pairs (ts > marker) are exported to Notion.

        last_published_meeting_ts (str): 
            Transactional marker (ISO Timestamp) for Meeting content.
            Prevents duplicate summaries from being posted to the Meeting History DB.
    """
    messages: Annotated[List[AnyMessage], add_messages]
    msg: Dict[str, Any]
    route: Optional[str]
    session_id: str
    config: Dict[str, Any]
    clarify_count: int
    summary: Optional[str]
    casual_conv: Annotated[Dict[str, Any], merge_dicts]
    retrieval_conv: Annotated[Dict[str, Any], merge_dicts]
    meeting_conv: Annotated[Dict[str, Any], merge_dicts]
    publishing_conv: Annotated[Dict[str, Any], merge_dicts]
    notion_workspace: Optional[Dict[str, Any]]
    last_published_retrieval_ts: str
    last_published_meeting_ts: str
    intent_data: Optional[Dict[str, Any]]
    export_mode: Optional[str]
    memory_payload: Optional[Dict[str, Any]]

def create_initial_state(session_id: str) -> AgentState:
    """
    Factory function to initialize a clean AgentState for a new session.
    
    Args:
        session_id (str): The unique ID for the session.
        
    Returns:
        AgentState: A fully initialized state dictionary with default values.
    """
    return {
        "messages": [],
        "msg": {
            "msg_id": "",
            "msg_content": "",
            "msg_body": {
                "answer": None,
                "decomposed_questions": [],
                "retrieval": [],
                "human_feedback": None
            }
        },
        "route": None,
        "session_id": session_id,
        "config": {},
        "clarify_count": 0,
        "summary": None,
        "casual_conv": {},
        "retrieval_conv": {},
        "meeting_conv": {},
        "publishing_conv": {},
        "notion_workspace": None,
        "last_published_retrieval_ts": "",
        "last_published_meeting_ts": "",
        "intent_data": None,
        "export_mode": "SYNTHESIS",
        "memory_payload": None
    }
